In [ ]:
import numpy as np

In [4]:
arr = np.array([[1,2,3],[4,5,6]]
              )

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr = np.array([[[1],[2]],[[3],[4]],[[5],[6]]]
              )

In [7]:
arr.shape


(3, 2, 1)

In [15]:
arr.squeeze

<function ndarray.squeeze>

In [16]:
arr.shape

(3, 2, 1)

In [17]:
arr.reshape(-1,2,3,1,1).flatten()

array([1, 2, 3, 4, 5, 6])

In [18]:
arr = np.array([[[1],[2]],[[3],[4]],[[5],[6]]])

In [19]:
arr[0]

array([[1],
       [2]])

In [20]:
arr[0:2]

array([[[1],
        [2]],

       [[3],
        [4]]])

In [21]:
arr[0:2,0,0]

array([1, 3])

In [22]:
arr[0,:,0].shape

(2,)

In [23]:
arr[...,0]

array([[1, 2],
       [3, 4],
       [5, 6]])